### ISSUE TITLE
manifest.in should have uppercase filename

### ISSUE THREAD

**Issue by hiciu** [dmulholland/ark#1]
Hi,

Under Linux (with python 3.5, setuptools 18.2) `manifest.in` with lowercase filename is ignored.

	% ls
	ark/  docs/  manifest.in  readme.md  ark.py*  setup.py*  license.txt
	% git status
	On branch master
	Your branch is up-to-date with 'origin/master'.
	nothing to commit, working directory clean
	% ../venv/bin/python setup.py build
	running build
	running build_py
	creating build
	creating build/lib
	creating build/lib/ark
	copying ark/extensions.py -> build/lib/ark
	copying ark/main.py -> build/lib/ark
	copying ark/records.py -> build/lib/ark
	copying ark/build.py -> build/lib/ark
	copying ark/templates.py -> build/lib/ark
	copying ark/site.py -> build/lib/ark
	copying ark/renderers.py -> build/lib/ark
	copying ark/pages.py -> build/lib/ark
	copying ark/hashes.py -> build/lib/ark
	copying ark/meta.py -> build/lib/ark
	copying ark/utils.py -> build/lib/ark
	copying ark/hooks.py -> build/lib/ark
	copying ark/config.py -> build/lib/ark
	copying ark/includes.py -> build/lib/ark
	copying ark/__init__.py -> build/lib/ark
	running egg_info
	creating ark.egg-info
	writing dependency_links to ark.egg-info/dependency_links.txt
	writing requirements to ark.egg-info/requires.txt
	writing top-level names to ark.egg-info/top_level.txt
	writing ark.egg-info/PKG-INFO
	writing entry points to ark.egg-info/entry_points.txt
	writing manifest file 'ark.egg-info/SOURCES.txt'
	reading manifest file 'ark.egg-info/SOURCES.txt'
	writing manifest file 'ark.egg-info/SOURCES.txt'

And uppercase version:

	% rm -rf ark.egg-info build
	% ls
	ark/  docs/  manifest.in  readme.md  ark.py*  setup.py*  license.txt
	% mv manifest.in MANIFEST.in
	% ls
	ark/  docs/  MANIFEST.in  readme.md  ark.py*  setup.py*  license.txt
	% git status
	On branch master
	Your branch is up-to-date with 'origin/master'.
	Changes not staged for commit:
	  (use "git add/rm <file>..." to update what will be committed)
	  (use "git checkout -- <file>..." to discard changes in working directory)
	        deleted:    manifest.in
	Untracked files:
	  (use "git add <file>..." to include in what will be committed)
	        MANIFEST.in
	no changes added to commit (use "git add" and/or "git commit -a")
	% ../venv/bin/python setup.py build
	running build
	running build_py
	creating build
	creating build/lib
	creating build/lib/ark
	copying ark/extensions.py -> build/lib/ark
	copying ark/main.py -> build/lib/ark
	copying ark/records.py -> build/lib/ark
	copying ark/build.py -> build/lib/ark
	copying ark/templates.py -> build/lib/ark
	copying ark/site.py -> build/lib/ark
	copying ark/renderers.py -> build/lib/ark
	copying ark/pages.py -> build/lib/ark
	copying ark/hashes.py -> build/lib/ark
	copying ark/meta.py -> build/lib/ark
	copying ark/utils.py -> build/lib/ark
	copying ark/hooks.py -> build/lib/ark
	copying ark/config.py -> build/lib/ark
	copying ark/includes.py -> build/lib/ark
	copying ark/__init__.py -> build/lib/ark
	running egg_info
	creating ark.egg-info
	writing top-level names to ark.egg-info/top_level.txt
	writing requirements to ark.egg-info/requires.txt
	writing ark.egg-info/PKG-INFO
	writing entry points to ark.egg-info/entry_points.txt
	writing dependency_links to ark.egg-info/dependency_links.txt
	writing manifest file 'ark.egg-info/SOURCES.txt'
	reading manifest file 'ark.egg-info/SOURCES.txt'
	reading manifest template 'MANIFEST.in'
	writing manifest file 'ark.egg-info/SOURCES.txt'
	creating build/lib/ark/ext
	copying ark/ext/cli.py -> build/lib/ark/ext
	copying ark/ext/dedup.py -> build/lib/ark/ext
	copying ark/ext/ibis_support.py -> build/lib/ark/ext
	copying ark/ext/jinja_support.py -> build/lib/ark/ext
	copying ark/ext/md_support.py -> build/lib/ark/ext
	copying ark/ext/pygmentize.py -> build/lib/ark/ext
	copying ark/ext/sc_support.py -> build/lib/ark/ext
	copying ark/ext/stx_support.py -> build/lib/ark/ext
	copying ark/ext/tags.py -> build/lib/ark/ext
	creating build/lib/ark/ini
	copying ark/ini/config.py -> build/lib/ark/ini
	creating build/lib/ark/ini/ext
	copying ark/ini/ext/paging.py -> build/lib/ark/ini/ext
	copying ark/ini/ext/report.py -> build/lib/ark/ini/ext
	creating build/lib/ark/ini/inc
	copying ark/ini/inc/menu.md -> build/lib/ark/ini/inc
	copying ark/ini/inc/sidebar.md -> build/lib/ark/ini/inc
	creating build/lib/ark/ini/lib
	creating build/lib/ark/ini/lib/debug
	copying ark/ini/lib/debug/license.txt -> build/lib/ark/ini/lib/debug
	copying ark/ini/lib/debug/readme.md -> build/lib/ark/ini/lib/debug
	creating build/lib/ark/ini/lib/debug/resources
	copying ark/ini/lib/debug/resources/pygments.css -> build/lib/ark/ini/lib/debug/resources
	copying ark/ini/lib/debug/resources/theme.css -> build/lib/ark/ini/lib/debug/resources
	creating build/lib/ark/ini/lib/debug/templates
	copying ark/ini/lib/debug/templates/base.ibis -> build/lib/ark/ini/lib/debug/templates
	copying ark/ini/lib/debug/templates/index.ibis -> build/lib/ark/ini/lib/debug/templates
	copying ark/ini/lib/debug/templates/single.ibis -> build/lib/ark/ini/lib/debug/templates
	creating build/lib/ark/ini/lib/twentyfifteen
	copying ark/ini/lib/twentyfifteen/license.txt -> build/lib/ark/ini/lib/twentyfifteen
	copying ark/ini/lib/twentyfifteen/readme.md -> build/lib/ark/ini/lib/twentyfifteen
	creating build/lib/ark/ini/lib/twentyfifteen/resources
	creating build/lib/ark/ini/lib/twentyfifteen/resources/css
	copying ark/ini/lib/twentyfifteen/resources/css/pygments.css -> build/lib/ark/ini/lib/twentyfifteen/resources/css
	copying ark/ini/lib/twentyfifteen/resources/css/theme.css -> build/lib/ark/ini/lib/twentyfifteen/resources/css
	creating build/lib/ark/ini/lib/twentyfifteen/resources/genericons
	copying ark/ini/lib/twentyfifteen/resources/genericons/COPYING.txt -> build/lib/ark/ini/lib/twentyfifteen/resources/genericons
	copying ark/ini/lib/twentyfifteen/resources/genericons/Genericons.eot -> build/lib/ark/ini/lib/twentyfifteen/resources/genericons
	copying ark/ini/lib/twentyfifteen/resources/genericons/Genericons.svg -> build/lib/ark/ini/lib/twentyfifteen/resources/genericons
	copying ark/ini/lib/twentyfifteen/resources/genericons/Genericons.ttf -> build/lib/ark/ini/lib/twentyfifteen/resources/genericons
	copying ark/ini/lib/twentyfifteen/resources/genericons/Genericons.woff -> build/lib/ark/ini/lib/twentyfifteen/resources/genericons
	copying ark/ini/lib/twentyfifteen/resources/genericons/LICENSE.txt -> build/lib/ark/ini/lib/twentyfifteen/resources/genericons
	copying ark/ini/lib/twentyfifteen/resources/genericons/README.md -> build/lib/ark/ini/lib/twentyfifteen/resources/genericons
	copying ark/ini/lib/twentyfifteen/resources/genericons/genericons.css -> build/lib/ark/ini/lib/twentyfifteen/resources/genericons
	creating build/lib/ark/ini/lib/twentyfifteen/resources/js
	copying ark/ini/lib/twentyfifteen/resources/js/html5shiv.min.js -> build/lib/ark/ini/lib/twentyfifteen/resources/js
	copying ark/ini/lib/twentyfifteen/resources/js/jquery-1.11.3.min.js -> build/lib/ark/ini/lib/twentyfifteen/resources/js
	copying ark/ini/lib/twentyfifteen/resources/js/theme.js -> build/lib/ark/ini/lib/twentyfifteen/resources/js
	creating build/lib/ark/ini/lib/twentyfifteen/templates
	copying ark/ini/lib/twentyfifteen/templates/base.ibis -> build/lib/ark/ini/lib/twentyfifteen/templates
	copying ark/ini/lib/twentyfifteen/templates/index.ibis -> build/lib/ark/ini/lib/twentyfifteen/templates
	copying ark/ini/lib/twentyfifteen/templates/single.ibis -> build/lib/ark/ini/lib/twentyfifteen/templates
	creating build/lib/ark/ini/src
	creating build/lib/ark/ini/src/[pages]
	copying ark/ini/src/[pages]/about.stx -> build/lib/ark/ini/src/[pages]
	copying ark/ini/src/[pages]/index.md -> build/lib/ark/ini/src/[pages]
	creating build/lib/ark/ini/src/[posts]
	copying ark/ini/src/[posts]/post-one.md -> build/lib/ark/ini/src/[posts]
	copying ark/ini/src/[posts]/post-two.md -> build/lib/ark/ini/src/[posts]

Version directly from repo (with lowercase `manifest.in`) is not functional:

```
% ./venv/bin/ark
Traceback (most recent call last):
  File "./venv/bin/ark", line 9, in <module>
    load_entry_point('ark==1.4.0', 'console_scripts', 'ark')()
  File "/home/hiciu/scratchspace/2016-02/07/temp2/venv/lib/python3.5/site-packages/ark/main.py", line 19, in main
    extensions.load()
  File "/home/hiciu/scratchspace/2016-02/07/temp2/venv/lib/python3.5/site-packages/ark/extensions.py", line 34, in load
    for name in os.listdir(dirpath):
FileNotFoundError: [Errno 2] No such file or directory: '/home/hiciu/scratchspace/2016-02/07/temp2/venv/lib/python3.5/site-packages/ark/ext'
```

**Comment by dmulholland** [comment]
That's interesting. I've only ever built the package on OSX and Windows and they both have case-insensitive filesystems so I'd never noticed before. Thanks for letting me know.

On the downside, I'd rather lick a leper than have a file named `MANIFEST.in` uglying up the repository... Know of any alternative way of including the required files?

**Comment by dmulholland** [comment]
Fixed. Got rid of the wretched file altogether. Works for me in Ubuntu. Can you let me know if this works okay for you and I'll push an update to PyPI?

**Comment by hiciu** [comment]
Hi,

Thanks. I can confirm that with 9e9331d2d1f325baa644ee43f070135aa3da8773 everything is OK. And I totally understand why you don't want `MANIFEST.in` in your repository :).

**Comment by dmulholland** [comment]
Bug squashed, ugliness averted - not bad for a Sunday :) Thanks for the report!
