### ISSUE TITLE
Ignore extensions

### ISSUE THREAD

**Issue by dmishin** [dmulholland/ark#3]
Is there a possibility to ignore some specific extensions (or all unknown extensions) in the src folder?

For now, it stops with error when stumbles file with unknown extension.

**Comment by dmulholland** [comment]
I just pushed a commit that should fix this for you. We now ignore any source files that don't have renderers registered for their file extensions.

Let me know if this works for you and I'll push an update to the package index.

**Comment by dmulholland** [comment]
Closing as fixed.
